### ISSUE TITLE
Dotty support

### ISSUE THREAD

**Issue by dwlizlo** [ReactiveMongo/ReactiveMongo#1010]
Are there any plans for Dotty/Scala3 support? Should we create the project or we expect no issues with migration?

**Comment by cchantep** [comment]
Hi,

As [documented](https://www.scala-lang.org/2019/12/18/road-to-scala-3.html#how-is-binary-compatibility-handled-in-scala-3), Scala 3 is supposed to be able to work with libraries built in Scala 2.13 (except macros).

Specific support is planned but not prioritized.

Also as [indicated](https://github.com/ReactiveMongo/ReactiveMongo/blob/master/.github/ISSUE_TEMPLATE.md#are-you-looking-for-help), use the [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) to ask questions rather than this issue tracker.

**Comment by cchantep** [comment]
Release Candidate 1.1.0-RC2 with Scala 3.1 support: https://t.co/D6wvpleYkd
