### ISSUE TITLE
Throwing exceptions on unique index violation

### ISSUE THREAD

**Issue by wertlex** [ReactiveMongo/ReactiveMongo#245]
In case of uniq index violation reactive mongo throws exception which is very inconsistent with lastError.
Is unique index violation really an exceptional situation?

Example:

```scala
bsonCollection.indexesManager.ensure(uniqIndexOnEmail)

bsonCollection.insert(bucket).map{ lastError =>
  if(lastError.ok)    \/-(identifiedUser)
  else                -\/(Reason.dbError)
}.recover {
  case e: Throwable => {
    println("HEHE. Really an exception!")
    -\/(Reason.dbError(""))
  }
}
```

**Comment by cchantep** [comment]
I guess by "reactive mongo throws exception" you mean the `Future` result is in `failed` state. To my mind, a duplicate index error is real error, that can be recovered (as in your example), or not if not supposed to happen.

This kind of discussion is welcome on the [user MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) (rather than on this issue tracker). Best regards.
