### ISSUE TITLE
How to perform a nearsphere find action?

### ISSUE THREAD

**Issue by 9cat** [ReactiveMongo/ReactiveMongo#374]
Suppose I want  perform a nearsphere like the following  :

          db.pois.find({"loc":{"$nearSphere":{"$geometry":{"type":"Point","coordinates":[118.606743,30.053336]},"$maxDistance":5000, "$minDistance":0}}})

How can I do  that by reactivemongo in Play framework?

**Comment by cchantep** [comment]
Hi, please first have a look at the [documentation](http://reactivemongo.org/releases/0.11/documentation/index.html) (see how to find documents). If you have a question not covered by this doc, then you can use the [user MailingList](https://groups.google.com/forum/m/?fromgroups#!forum/reactivemongo) rather than this issue tracker. Best regards.
