### ISSUE TITLE
Compiler warning when using aggregation API

### ISSUE THREAD

**Issue by peterschrott** [ReactiveMongo/ReactiveMongo#739]
### ReactiveMongo Version
0.13.0

### MongoDB version
3.6

### Operating System
MacOS 10.13

### JDK
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
### Scala 
Scala code runner version 2.12.4 -- Copyright 2002-2017, LAMP/EPFL and Lightbend, Inc.

### Expected Behavior

Usage of aggregation api on collection (`BSONCollection.aggregate(.)`) should compile without warning.

Usage of the sbt compiler flag `-Xfatal-warnings` makes compiler warnings to compiler errors.

No compiler warnings for the library.

### Actual Behavior

The usage of the above stated function leads to an compiler warning as the type of the function is the deprecated type `AggregationResult`.

Usage of the compiler flag `-Xfatal-warnings` won't let me my project compile as the depreciation warning leads to a compiler error.

`sbt compile` leads to the following warning:
`class AggregationResult in trait AggregationFramework is deprecated (since 0.12.7): Use 'api.collections.Aggregator'`

**Comment by cchantep** [comment]
Hi,

The root warning is the usage of `.aggregate`, deprecated since 0.12.3.
You can have a look at the [API documentation](http://reactivemongo.org/releases/0.1x/api/reactivemongo/api/collections/GenericCollection.html#aggregatorContext[T](firstOperator:GenericCollection.this.PipelineOperator,otherOperators:List[GenericCollection.this.PipelineOperator],explain:Boolean,allowDiskUse:Boolean,bypassDocumentValidation:Boolean,readConcern:Option[reactivemongo.api.ReadConcern],readPreference:reactivemongo.api.ReadPreference,batchSize:Option[Int])(implicitreader:GenericCollection.this.pack.Reader[T]):GenericCollection.this.AggregatorContext[T]).

BTW, rather use either the [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo), or [SO](https://stackoverflow.com/tags/reactivemongo/info) to ask question/for help (this tracker is for confirmed issue or actionable feature request).

Best regards.

**Comment by peterschrott** [comment]
Hi @cchantep, 

thanks for your quick answer. 

But form the [docs](http://reactivemongo.org/releases/0.1x/api/reactivemongo/api/collections/GenericCollection.html#aggregate(firstOperator:GenericCollection.this.PipelineOperator,otherOperators:List[GenericCollection.this.PipelineOperator],explain:Boolean,allowDiskUse:Boolean,bypassDocumentValidation:Boolean,readConcern:Option[reactivemongo.api.ReadConcern])(implicitec:scala.concurrent.ExecutionContext):scala.concurrent.Future[GenericCollection.this.BatchCommands.AggregationFramework.AggregationResult]) I can see, that `GenericCollection.aggregate(.)` is not annotated as deprecated. Only the typed version of it is so.

The [official documentation ](http://reactivemongo.org/releases/0.1x/documentation/advanced-topics/aggregation.html)also encourages to use `BSONCollection.aggregate(.)`.

**Comment by cchantep** [comment]
The [documentation](http://reactivemongo.org/releases/0.1x/documentation/advanced-topics/aggregation.html) indicates how to use [`.aggregatorContext`](http://reactivemongo.org/releases/0.1x/documentation/advanced-topics/aggregation.html).
